In [4]:
# Install Numpy
!pip install numpy

In [2]:
# Import numpy
import numpy as np

In [6]:
# Numpy version installed in the system
print(np.__version__)

2.1.3


In [ ]:
# 1. Creating arrays

In [ ]:
list1 = [1,2,3]
print(list1)

In [8]:
# creating array using list
arr_list = np.array(list1)
print(arr_list)

[1 2 3]


In [9]:
# check datatype of vsriable
print(type(arr_list))

<class 'numpy.ndarray'>


In [10]:
# Check dimension of array
print(arr_list.ndim)

1


In [13]:
# Creating 2dim using 2 list
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1_2 = np.array([list1,list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [14]:
# Check dimension of array
print(arr_list1_2.ndim)

2


In [16]:
# Creating 3 dim array using 3 list
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list1_3 = np.array([[list1,list2,list3]])
print(arr_list1_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [17]:
# Check dimension of array
print(arr_list1_3.ndim)

3


In [ ]:
# 2. Numpy array attributes

In [19]:
arr1= np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [20]:
#Attributes of aray (properties of array)

# shape = row, columns and height of array
print(arr1.shape)


(2, 3)


In [21]:
# number of elements of array
print(arr1.size)

6


In [22]:
# data type of element of array
print(arr1.dtype)

int64


In [23]:
# dimension of array
print(arr1.ndim)

2


In [ ]:
# 3. Array initialization methods


In [25]:
# zero array : all elements are 0
zero_arr = np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
# ones array : all elements are 1
one_arr = np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# full array : all elements are same based on given values
full_arr = np.full((2,3),5)
print(full_arr)

[[5 5 5]
 [5 5 5]]


In [29]:
# identity matrix : diagonal elements are ones and all other elements are zeros
id_arr = np.eye(6)
print(id_arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [30]:
# empty array
print(np.empty(2))

[9.9e-324 1.5e-323]


In [31]:
# evenly spaced array : elements are evenly spaced based on step value
print(np.arange(2,10,2))

[2 4 6 8]


In [32]:
# spacific number of equaly spaced values between a range : elements are equaly spaced on sep value
print(np.linspace(2,11,4))

[ 2.  5.  8. 11.]


In [33]:
# random value array - float
r_rr = np.random.rand(3,2)
print(r_rr)

[[0.21139726 0.51645624]
 [0.52583106 0.43532551]
 [0.01230852 0.46477972]]


In [34]:
# random value array - int
rint_arr = np.random.randint(1,100,(3,3))
print(rint_arr)


[[66  5 81]
 [29 80  9]
 [90 71 72]]


In [5]:
# 4. Array indexing and slicing
a = np.array([1,2,3,5,7,9])
print(a)

[1 2 3 5 7 9]


In [6]:
# first element of array
print(a[0])

1


In [7]:
# fifth element of array
print(a[4])

7


In [8]:
# last element of erray
print(a[-1])

9


In [10]:
a = np.array([1,3,5,7,9])
print(a)
# Slicing 
# Array[start : stop : step]
# stop - indexing, that is not included in output

[1 3 5 7 9]


In [16]:
# last 3 element
print(a[-3:])

[5 7 9]


In [17]:
# first 3 element
print(a[:3])

[1 3 5]


In [19]:
# middle 3 element
print(a[1:3])

[3 5]


In [20]:
# middle 3 element with steps
print(a[:3:3])

[1]


In [23]:
# all alternative element with step
print(a[0::2])
print(a[0::])
print(a[::])

[1 5 9]
[1 3 5 7 9]
[1 3 5 7 9]


In [25]:
# Indexing on 2 Dimension Array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

# 2D Array: [rows, columns]                    2d Array take 2 values - rows and columns for indexing
# 3D Array: [layers/height, row, columns]      3D Array take 3 values - height, rows and columns for indexing




[[1 2 3]
 [4 5 6]]


In [38]:
print("first row = ",arr2[0])
print("second row =",arr2[1])

first row =  [1 2 3]
second row = [4 5 6]


In [33]:
# Slicing on 2D array

# element of 1st row and 1st column
print(arr2[0][0])

# element of 1st row and 2nd column
print(arr2[0][1])

# element od 2nd row and 3rd column
print(arr2[1][2])

1
2
6


In [34]:
# specific element 1D
print(arr2[1])

[4 5 6]


In [35]:
# slicing part 2D
print(arr2[1:])

[[4 5 6]]


In [36]:
print(arr2)
# 2D Aeear: [rows, columns]
# eg: arr2[0][1]
# 2D Array take 2 values - row and column for indexing

[[1 2 3]
 [4 5 6]]


In [42]:
# first column of an array
print(arr2[:,0])

[1 4]


In [44]:
# second column of an array
print(arr2[0:,1])

[2 5]


In [45]:
# third column of array
print(arr2[0:2])

[[1 2 3]
 [4 5 6]]


In [63]:
arr3 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr3)

# 3D Array: [layers/height, row, columns]
# 3D array take 3 values - height, rows and columns for indexing

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
print(arr3[0])

[1 2 3]


In [69]:
print(arr3[1])

[4 5 6]


In [71]:
print(arr3[2])

[7 8 9]


In [72]:
print(arr3[0][2])

3


In [73]:
print(arr3[2][2])

9


In [74]:
# 1st column value
print(arr3[:,0])

[1 4 7]


In [75]:
# 2nd column value
print(arr3[:,1])

[2 5 8]


In [78]:
# 3rd column row
print(arr3[:,2])

[3 6 9]


In [81]:
# slicing on columns
print(arr3[::,0:1])

[[1]
 [4]
 [7]]


In [82]:
# slicing on rows and columns
print(arr3[2::,1:2])

[[8]]


In [83]:
# 5. Array reshaping and flattening



In [84]:
# Reshape Array: changing it's dimension (e.g., row and columns) without altering the actual data
# Flatten array: transformational a multi-dimensional array into a single-dimensional array



In [86]:
# shape = (1,6) - 1 row and 6 column
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [87]:
# shape = (6,1) -6 rows and 1 column
reshaped = arr1.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [88]:
# reshaped array from (1,6) to (2,3)

reshaped2 = arr1.reshape((2,3))
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [91]:
# flattened array from higher (2D) dimensional (2,3) to (1,6) (1D)
print(reshaped2.flatten())




[1 2 3 4 5 6]


In [ ]:
#6. Array Stacking and Splitting

In [92]:
# Array Stacking: combining multple arrays aling a new axis, resulting in an array with a higher dimension than the input arrays
# Array Splitting:


In [94]:
# Staking 
a = np.array([1,2,3])
b = np.array([4,5,6])

# vertical stackling - row wise  -> output is 2D
print(np.vstack((a,b)))

# horizantal stacking - column wise
print(np.hstack((a)))

[[1 2 3]
 [4 5 6]]
[1 2 3]


In [95]:
# splitting
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [97]:
# horizontal split -> input and output aray are same dimention

hsplit = np.hsplit(c,3)
for s in hsplit:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [98]:
# bertical split -> input and output array are same dimention
vsplit = np.vsplit(c,2)

for s in vsplit:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [99]:
# 8. Mathematical Operations on Multiple arrays


In [100]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [102]:
# Add two arrays
print(np.add(a,b))

[5 7 9]


In [103]:
# Subtract two array
print(np.subtract(a,b))

[-3 -3 -3]


In [104]:
# multipul two array
print(np.multiply(a,b))

[ 4 10 18]


In [105]:
# divide two array
print(np.divide(a,b))

[0.25 0.4  0.5 ]


In [106]:
# Dot product: computes the inner product of the two vectors and sum the results
print(np.dot(a,b))

32


In [107]:
#Transpose: Returns an array with axes transposed
print(a.T)

[1 2 3]


In [108]:
t = np.array([[1,2,3],[4,5,6]])
print(t)       #initial shape: 2,3
print(t.T)     #shape after transpose

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [109]:
# 9. Statistical Function 
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [110]:
print(np.sum(a))

21


In [111]:
print(np.mean(a))

3.5


In [112]:
print(np.median(a))

3.5


In [113]:
print(np.std(a))

1.707825127659933


In [114]:
print(np.min(a))

1


In [115]:
print(np.max(a))

6


In [117]:
# 10. Array Comparison
a = np.array([1,5,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 5 3]
[4 5 6]


In [118]:
# comparing each element of an array
print( a== b)

[False  True False]


In [119]:
# comparing  complete array
print(np.array_equal(a,b))

False


In [ ]:
# 11. Broadcasting

# Broadcasting: is a mechanism that allow arithmetic to be performed on arrays of different shapes and sizes,
# it eliminates the need for explicit loops or reshaping operating, making code more concise, readable and efficient.

# Broadcasting Rules:
   # comparing shapes from right to left.
   # Dimensions must match or be 1.
   # If one array has fewer dimensions, pad its shape on the left with is.
   # Any dimension equal to 1 can stretch to match the other array.
   


In [121]:
a = np.array([1,2,3,4])
b = np.array([5])
print(a+b)       # adding 1D with One-element Array to 1D with multi-element array

[6 7 8 9]


In [124]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([10,20,30])
print(c+d)            # adding 2D with 6-element array(2,3) to 1D with 6-element array


[[11 22 33]
 [14 25 36]]


In [125]:
# 12. Handlling with nan & inf

In [127]:
data1 = np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [130]:
# check null value and returns boolean value
print(np.isnan(data1))

[False False  True False False]


In [131]:
print(np.nan_to_num(data1))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]
